# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ws_sync_client"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2014-03-14"
  s.description = "WebSocket client that does not require asynchronous programming"
  s.email = "costan@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ws_sync_client.rb",
    "test/fixtures/ws_server.rb",
    "test/helper.rb",
    "test/test_ws_sync_client.rb"
  ]
  s.homepage = "http://github.com/pwnall/ws_sync_client"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Synchronous WebSocket client"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<websocket>, [">= 1.1.2"])
      s.add_runtime_dependency(%q<websocket-native>, [">= 1.0.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.5.3"])
      s.add_development_dependency(%q<debugger>, [">= 1.6.6"])
      s.add_development_dependency(%q<em-websocket>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<minitest>, [">= 5.3.0"])
      s.add_development_dependency(%q<rdoc>, [">= 4.1.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0.8.2"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.3"])
    else
      s.add_dependency(%q<websocket>, [">= 1.1.2"])
      s.add_dependency(%q<websocket-native>, [">= 1.0.0"])
      s.add_dependency(%q<bundler>, [">= 1.5.3"])
      s.add_dependency(%q<debugger>, [">= 1.6.6"])
      s.add_dependency(%q<em-websocket>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<minitest>, [">= 5.3.0"])
      s.add_dependency(%q<rdoc>, [">= 4.1.1"])
      s.add_dependency(%q<simplecov>, [">= 0.8.2"])
      s.add_dependency(%q<yard>, [">= 0.8.7.3"])
    end
  else
    s.add_dependency(%q<websocket>, [">= 1.1.2"])
    s.add_dependency(%q<websocket-native>, [">= 1.0.0"])
    s.add_dependency(%q<bundler>, [">= 1.5.3"])
    s.add_dependency(%q<debugger>, [">= 1.6.6"])
    s.add_dependency(%q<em-websocket>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<minitest>, [">= 5.3.0"])
    s.add_dependency(%q<rdoc>, [">= 4.1.1"])
    s.add_dependency(%q<simplecov>, [">= 0.8.2"])
    s.add_dependency(%q<yard>, [">= 0.8.7.3"])
  end
end

