# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ws_sync_client 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "ws_sync_client".freeze
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Victor Costan".freeze]
  s.date = "2017-06-25"
  s.description = "WebSocket client that does not require asynchronous programming".freeze
  s.email = "costan@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/ws_sync_client.rb",
    "test/fixtures/ws_server.rb",
    "test/helper.rb",
    "test/test_ws_sync_client.rb",
    "ws_sync_client.gemspec"
  ]
  s.homepage = "http://github.com/pwnall/ws_sync_client".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Synchronous WebSocket client".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<websocket>.freeze, [">= 1.2.4"])
      s.add_runtime_dependency(%q<websocket-native>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.5.3"])
      s.add_development_dependency(%q<byebug>.freeze, [">= 9.0.6"])
      s.add_development_dependency(%q<em-websocket>.freeze, [">= 0.5.1"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.7"])
      s.add_development_dependency(%q<minitest>.freeze, [">= 5.3.0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 5.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0.9.9"])
    else
      s.add_dependency(%q<websocket>.freeze, [">= 1.2.4"])
      s.add_dependency(%q<websocket-native>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.5.3"])
      s.add_dependency(%q<byebug>.freeze, [">= 9.0.6"])
      s.add_dependency(%q<em-websocket>.freeze, [">= 0.5.1"])
      s.add_dependency(%q<jeweler>.freeze, [">= 2.3.7"])
      s.add_dependency(%q<minitest>.freeze, [">= 5.3.0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 5.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
      s.add_dependency(%q<yard>.freeze, [">= 0.9.9"])
    end
  else
    s.add_dependency(%q<websocket>.freeze, [">= 1.2.4"])
    s.add_dependency(%q<websocket-native>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.5.3"])
    s.add_dependency(%q<byebug>.freeze, [">= 9.0.6"])
    s.add_dependency(%q<em-websocket>.freeze, [">= 0.5.1"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.7"])
    s.add_dependency(%q<minitest>.freeze, [">= 5.3.0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 5.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
    s.add_dependency(%q<yard>.freeze, [">= 0.9.9"])
  end
end

